name: Build Linux Standalone

on:
  push:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Extract version from Python file
        id: get_version
        run: |
          VERSION=$(grep '__version__' generador.py | cut -d '"' -f2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build executable
        run: |
          wordlist_path=$(python3 -c "import bip_utils, os; print(os.path.join(os.path.dirname(bip_utils.__file__), 'bip', 'bip39', 'wordlist'))")
          pyinstaller --onefile generador.py --name helltrackr \
            --add-data "$wordlist_path/*.txt:bip_utils/bip/bip39/wordlist" \
            --hidden-import=coincurve._libsecp256k1 \
            --hidden-import=coincurve._cffi_backend \
            --hidden-import=_cffi_backend

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          files: dist/helltrackr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
